### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by TobiGr** [mhmdanas/test-waiting-for-author-script#4]
This issue is missing information :)

**Comment by triallax** [comment]
Hmm, should I make the script listen to comments and if the author comments, remove the label automatically, or leave that up to issue maintainers?

**Comment by TobiGr** [comment]
Maybe add another label `author-replied` making it obvious for maintainers that a state change happened and some action is required by us.

Is the issue reopened by the bot or does the author need to reopen the issue manually?

**Comment by triallax** [comment]
Test
